// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwgj7yreLWL4BM-mUZWlVcV2sCsrT-F40',
    appId: '1:15879392615:android:9520b260dce551c141b3c2',
    messagingSenderId: '15879392615',
    projectId: 'music-player-ffb8c',
    storageBucket: 'music-player-ffb8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVVSUh69SEHo4XZI838LJ17dJnoE91VLY',
    appId: '1:15879392615:ios:d4d1f94917dfc03f41b3c2',
    messagingSenderId: '15879392615',
    projectId: 'music-player-ffb8c',
    storageBucket: 'music-player-ffb8c.firebasestorage.app',
    iosBundleId: 'com.example.appcontainer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVhDPQNDNPrhUrKIvgda6jnvJ-Bb2lO0o',
    appId: '1:15879392615:web:d74a55c04fcac8ad41b3c2',
    messagingSenderId: '15879392615',
    projectId: 'music-player-ffb8c',
    authDomain: 'music-player-ffb8c.firebaseapp.com',
    storageBucket: 'music-player-ffb8c.firebasestorage.app',
    measurementId: 'G-YND3C41WRK',
  );
}
